import { ACCEPTED_MIME_TYPES } from '@cvent/nucleus-file-upload/lib/types/helpers/mimeTypes';

export const SUPPORTED_VIDEO_TYPES: ACCEPTED_MIME_TYPES[] = [
  'mpg2',
  'mov',
  'mp4',
  'mpe',
  'mpeg',
  'mpg',
  'mpv',
  'qt',
  'webm'
];
export const COLOR = '#F7F8F9';
export const BACKGROUND_COLOR = '#0F0D23';
export const MAX_FILE_SIZE = 15_000_000_000;

export const LANGUAGES: LanguageType[] = [
  { label: 'Albanian (Albania)', value: 'sq-AL' },
  { label: 'Arabic (Algeria)', value: 'ar-DZ' },
  { label: 'Arabic (Bahrain)', value: 'ar-BH' },
  { label: 'Arabic (Egypt)', value: 'ar-EG' },
  { label: 'Arabic (Iraq)', value: 'ar-IQ' },
  { label: 'Arabic (Jordan)', value: 'ar-JO' },
  { label: 'Arabic (Kuwait)', value: 'ar-KW' },
  { label: 'Arabic (Lebanon)', value: 'ar-LB' },
  { label: 'Arabic (Libya)', value: 'ar-LY' },
  { label: 'Arabic (Morocco)', value: 'ar-MA' },
  { label: 'Arabic (Oman)', value: 'ar-OM' },
  { label: 'Arabic (Qatar)', value: 'ar-QA' },
  { label: 'Arabic (Saudi Arabia)', value: 'ar-SA' },
  { label: 'Arabic (Sudan)', value: 'ar-SD' },
  { label: 'Arabic (Syria)', value: 'ar-SY' },
  { label: 'Arabic (Tunisia)', value: 'ar-TN' },
  { label: 'Arabic (United Arab Emirates)', value: 'ar-AE' },
  { label: 'Arabic (Yemen)', value: 'ar-YE' },
  { label: 'Belarusian (Belarus)', value: 'be-BY' },
  { label: 'Bengali (India)', value: 'bn-IN' },
  { label: 'Bengali (Bangladesh)', value: 'bn-BD' },
  { label: 'Bulgarian (Bulgaria)', value: 'bg-BG' },
  { label: 'Catalan (Spain)', value: 'ca-ES' },
  { label: 'Chinese (China)', value: 'zh-CN' },
  { label: 'Chinese (Hong Kong)', value: 'zh-HK' },
  { label: 'Chinese (Singapore)', value: 'zh-SG' },
  { label: 'Chinese (Taiwan)', value: 'zh-TW' },
  { label: 'Croatian (Croatia)', value: 'hr-HR' },
  { label: 'Czech (Czech Republic)', value: 'cs-CZ' },
  { label: 'Danish (Denmark)', value: 'da-DK' },
  { label: 'Dutch (Belgium)', value: 'nl-BE' },
  { label: 'Dutch (Netherlands)', value: 'nl-NL' },
  { label: 'English (Australia)', value: 'en-AU' },
  { label: 'English (Canada)', value: 'en-CA' },
  { label: 'English (India)', value: 'en-IN' },
  { label: 'English (Ireland)', value: 'en-IE' },
  { label: 'English (Malta)', value: 'en-MT' },
  { label: 'English (New Zealand)', value: 'en-NZ' },
  { label: 'English (Philippines)', value: 'en-PH' },
  { label: 'English (Singapore)', value: 'en-SG' },
  { label: 'English (South Africa)', value: 'en-ZA' },
  { label: 'English (United Kingdom)', value: 'en-GB' },
  { label: 'English (United States)', value: 'en-US' },
  { label: 'Estonian (Estonia)', value: 'et-EE' },
  { label: 'Finnish (Finland)', value: 'fi-FI' },
  { label: 'French (Belgium)', value: 'fr-BE' },
  { label: 'French (Canada)', value: 'fr-CA' },
  { label: 'French (France)', value: 'fr-FR' },
  { label: 'French (Luxembourg)', value: 'fr-LU' },
  { label: 'French (Switzerland)', value: 'fr-CH' },
  { label: 'German (Austria)', value: 'de-AT' },
  { label: 'German (Germany)', value: 'de-DE' },
  { label: 'German (Luxembourg)', value: 'de-LU' },
  { label: 'German (Switzerland)', value: 'de-CH' },
  { label: 'Greek (Cyprus)', value: 'el-CY' },
  { label: 'Greek (Greece)', value: 'el-GR' },
  { label: 'Hebrew (Israel)', value: 'iw-IL' },
  { label: 'Hindi (India)', value: 'hi-IN' },
  { label: 'Hungarian (Hungary)', value: 'hu-HU' },
  { label: 'Icelandic (Iceland)', value: 'is-IS' },
  { label: 'Indonesian (Indonesia)', value: 'in-ID' },
  { label: 'Irish (Ireland)', value: 'ga-IE' },
  { label: 'Italian (Italy)', value: 'it-IT' },
  { label: 'Italian (Switzerland)', value: 'it-CH' },
  { label: 'Japanese (Japan)', value: 'ja-JP' },
  { label: 'Korean (South Korea)', value: 'ko-KR' },
  { label: 'Latvian (Latvia)', value: 'lv-LV' },
  { label: 'Lithuanian (Lithuania)', value: 'lt-LT' },
  { label: 'Macedonian (Macedonia)', value: 'mk-MK' },
  { label: 'Malay (Malaysia)', value: 'ms-MY' },
  { label: 'Maltese (Malta)', value: 'mt-MT' },
  { label: 'Norwegian (Norway)', value: 'no-NO' },
  { label: 'Polish (Poland)', value: 'pl-PL' },
  { label: 'Portuguese (Brazil)', value: 'pt-BR' },
  { label: 'Portuguese (Portugal)', value: 'pt-PT' },
  { label: 'Romanian (Romania)', value: 'ro-RO' },
  { label: 'Russian (Russia)', value: 'ru-RU' },
  { label: 'Serbian (Bosnia and Herzegovina)', value: 'sr-BA' },
  { label: 'Serbian (Montenegro)', value: 'sr-ME' },
  { label: 'Serbian (Serbia and Montenegro)', value: 'sr-CS' },
  { label: 'Serbian (Serbia)', value: 'sr-RS' },
  { label: 'Slovak (Slovakia)', value: 'sk-SK' },
  { label: 'Slovenian (Slovenia)', value: 'sl-SI' },
  { label: 'Spanish (Argentina)', value: 'es-AR' },
  { label: 'Spanish (Bolivia)', value: 'es-BO' },
  { label: 'Spanish (Chile)', value: 'es-CL' },
  { label: 'Spanish (Colombia)', value: 'es-CO' },
  { label: 'Spanish (Costa Rica)', value: 'es-CR' },
  { label: 'Spanish (Dominican Republic)', value: 'es-DO' },
  { label: 'Spanish (Ecuador)', value: 'es-EC' },
  { label: 'Spanish (El Salvador)', value: 'es-SV' },
  { label: 'Spanish (Guatemala)', value: 'es-GT' },
  { label: 'Spanish (Honduras)', value: 'es-HN' },
  { label: 'Spanish (Mexico)', value: 'es-MX' },
  { label: 'Spanish (Nicaragua)', value: 'es-NI' },
  { label: 'Spanish (Panama)', value: 'es-PA' },
  { label: 'Spanish (Paraguay)', value: 'es-PY' },
  { label: 'Spanish (Peru)', value: 'es-PE' },
  { label: 'Spanish (Puerto Rico)', value: 'es-PR' },
  { label: 'Spanish (Spain)', value: 'es-ES' },
  { label: 'Spanish (United States)', value: 'es-US' },
  { label: 'Spanish (Uruguay)', value: 'es-UY' },
  { label: 'Spanish (Venezuela)', value: 'es-VE' },
  { label: 'Swedish (Sweden)', value: 'sv-SE' },
  { label: 'Thai (Thailand)', value: 'th-TH' },
  { label: 'Turkish (Turkey)', value: 'tr-TR' },
  { label: 'Ukrainian (Ukraine)', value: 'uk-UA' },
  { label: 'Vietnamese (Vietnam)', value: 'vi-VN' }
];

export type LanguageType = {
  label: string;
  value: string;
};

export const AVAILABLE_LOCALES: LanguageType[] = [
  { label: 'German (Germany)', value: 'de-DE' },
  { label: 'English (United States)', value: 'en-US' },
  { label: 'Spanish (Spain)', value: 'es-ES' },
  { label: 'Finnish (Finland)', value: 'fi-FI' },
  { label: 'French (Canada)', value: 'fr-CA' },
  { label: 'French (France)', value: 'fr-FR' },
  { label: 'Italian (Italy)', value: 'it-IT' },
  { label: 'Japanese (Japan)', value: 'ja-JP' },
  { label: 'Korean (South Korea)', value: 'ko-KR' },
  { label: 'Dutch (Netherlands)', value: 'nl-NL' },
  { label: 'Portuguese (Brazil)', value: 'pt-BR' },
  { label: 'Portuguese (Portugal)', value: 'pt-PT' },
  { label: 'Russian (Russia)', value: 'ru-RU' },
  { label: 'Swedish (Sweden)', value: 'sv-SE' },
  { label: 'Thai (Thailand)', value: 'th-TH' },
  { label: 'Turkish (Turkey)', value: 'tr-TR' },
  { label: 'Chinese (Simplified)', value: 'zh-CN' } /* ToDo: Support zh-Hans, zh-hant format for Chinese. */,
  { label: 'Chinese (Traditional)', value: 'zh-TW' }
];
export const MODAL_ZINDEX = 1100;
export const videoStorageEnforcementDate = new Date(2023, 2, 7);
export const ALLOW_LIMITED_VIEWS_BEFORE_LOGIN_COUNT_DEFAULT_VALUE = 3;
export const TOOLTIP_MAX_LENGTH = 285;
export const MAXIMUM_MEMBERS_SELECTIONS_FOR_DELETION = 200;
export const CCPA_EXPLANATION_TEXT_MAX_LIMIT = 2200;
export const BACKGROUND_IMAGE_ALT_TEXT_MAX_LIMIT = 100;
export const ACTIVE_HUB = 'Active';
export const HTTPS = 'https://';
